### ISSUE TITLE
Updating with chocolatey fails if NotifyMeCI.GUI.exe is currently running

### ISSUE THREAD

**Issue by admsteck** [Badgerati/NotifyMeCI#17]
It would be nice if any running instances would automatically be killed before the update is attempted.  Even better would be to restart it after the update if it was running before.

**Comment by Badgerati** [comment]
This should definitely be possible, I've had to do something similar with mmc.exe processes once before; helped more with the fact choco is normally run as admin anyway.

I'll look into it.

**Comment by Badgerati** [comment]
I've updated the `chocolateyInstall.ps1` so it now closes and re-opens any instanced of NotifyMeCI. I've also added a new `chocolateyUninstall.ps1` which does the same.

**Comment by admsteck** [comment]
I think the problem is before chocolateyInstall.ps1 is called.  It looks like chocolatey tries to move the contents of the existing chocolatey/lib/notify-me-ci into lib-bkp before the install.  I started looking at stopping any existing processes with the chocolateyBeforeModity.ps1 that was added in choco v9.10.

**Comment by Badgerati** [comment]
Wasn't even aware `chocolateyBeforeModify.ps1` was a thing! Looks like it's called before an upgrade/uninstall so can definitely kill the processes there.

Only issue then would be re-opening afterwards; as all context of killing those processes in `chocolateyInstall.ps1` will have been lost. It could be possible, but the only way I have in mind is super-hacky - ie, creating a temp `.reopen` file, then deleting it after the install.

**Comment by admsteck** [comment]
Will the .reopen file get deleted when choco does the upgrade though?  I wonder if the beforemodify and install scripts run under the same powershell host, then we could just set and remove a powershell variable respectively.  If not, an environment variable might work.  I was working on a beforemodify script using the powershell `get-process` and `stop-process` commands, but the problem I was having is that it was returning before all the file locks were completely released.

**Comment by Badgerati** [comment]
It will, the `chocolateyInstall.ps1` script is called on install/upgrade; so if the file exists it'll delete it.

I noticed that myself with Stop-Process when doing the mmc.exe stuff, it was one of the reasons I went with `taskkill` in the end.

**Comment by Badgerati** [comment]
I'll try the env/variables out, see if it works.

**Comment by Badgerati** [comment]
After testing, variables and environment variables don't seem to work. I tried Chocolatey's inbuilt environment variable installers, and then just tried the general `[Environment]` library; looks like the session deletes them after running each script, or something else is going on behind the scenes.

I'll stick to the `.reopen` file for now, as it works.
