### ISSUE TITLE
Add the option to startup to system tray

### ISSUE THREAD

**Issue by admsteck** [Badgerati/NotifyMeCI#18]
Add the option to startup minimized without showing a window and only showing the icon in the system tray.  Either as a configurable option in the app, or a command line parameter.

**Comment by Badgerati** [comment]
I've set it so you can use both methods:
- For the command line argument, you can pass either `-m` or `--minimize` and the app will start in the system tray.
- For the configurable setting within the app: there is a new `Settings` menu with a checkbox. This value will be respected on app start-up.

If either the command line argument is passed, or the in-app minimize checkbox setting is checked, then the app will start-up in the system tray.
