### ISSUE TITLE
Settings are not retained when upgrading

### ISSUE THREAD

**Issue by admsteck** [Badgerati/NotifyMeCI#21]
Chocolatey removes the entire notify-me-ci folder when upgrading, so the server list which is stored in the folder is lost.

**Comment by Badgerati** [comment]
I was keeping an eye on this while testing with #17. Doing a normal `choco upgrade notify-me-ci -y` kept everything intact for me; the only time I could reproduce this was when I did `choco upgrade notify-me-ci -y --force`. The `--force` seems to skip the beforeModify, ditch the entire directory and do a complete re-install - it doesn't even call the uninstall script.

**Comment by admsteck** [comment]
That could be. I was doing all sorts of uninstalls, installs, and upgrades when trying different things for #17.

**Comment by Badgerati** [comment]
Not even `--force` for me causes this any more, maybe I was doing something weird as well.

Just while I can't seem to get this to happen, I'm going to close the issue. If it starts to cause major issues or you figure out a way to reproduce it constantly, re-open and let me know.
