### ISSUE TITLE
Option to treat aborted builds differently than failed builds

### ISSUE THREAD

**Issue by admsteck** [Badgerati/NotifyMeCI#25]
Currently, NotifyMeCI treats aborted builds similar to failed jobs.  They are sorted in the list above successful jobs and the icon in the tray is changed to red.  I would like the option to treat them similar to disabled or not built jobs since aborting a job may be for reasons that do not indicate a failure or something that needs attention.

I have a branch for a simple version of this option already, but I'm not sure how far you would like to take it.  My simple solution was to add a checkbox to the settings form, and change the sort order and color for aborted jobs based on the value of the checkbox.  If that sounds good I'll submit a pull request.  I just wanted to see if you liked this solution or would prefer a more complex but flexible solution like allowing the user specify the sort order and color of build status types.

**Comment by Badgerati** [comment]
Sorry for the late response, I was on holiday.

Your former solution was actually what I was thinking of while reading. The latter option ran through my mind, but for this I say let's go for the solution you already have.

I'll write up the latter idea as another issue in a bit, for a full feature as we might be able to get some other useful features in there too; like hiding builds with a certain status (such as loads of disabled builds).

If you're all right for me to create this as a new feature issue, go ahead an pull request your former fix.
