### ISSUE TITLE
Duration column in main window needs to display more friendly values

### ISSUE THREAD

**Issue by admsteck** [Badgerati/NotifyMeCI#36]
Currently, the duration column always shows the value as seconds.  For builds that take a few minutes to complete, it would be more helpful to see 23mins 42secs, or 00:23:42 instead of 1422secs.

**Comment by Badgerati** [comment]
Sorry about the lateness on this one.

I've changed it so that durations now appear as "1h 2m 3s", so a bit of a combination of both suggestions.
